version: '3.8'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npx wait-on tcp:db:3306 && node fixtures/seed.js && node src/app.js"

volumes:
  db-data: